spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogcice
    username: root
    password: root
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  serviceUri:
    default: http://localhost:8080/eureka-server
