spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: p4SSW0rd
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
