spring:
  datasource:
    url: jdbc:mysql://localhost:8889/blogcice
    username: root
    password: root
    platform: mysql
    initialize: false
  jpa:
database-platform: org.hibernate.dialect.MySQLDialect
